--// 通知系统（隐藏 GitHub）
local function _N()
    local s,r=pcall(function()
        loadstring(game:HttpGet("https://is.gd/stx_module"))()
        return loadstring(game:HttpGet("https://is.gd/stx_client"))()
    end)
    if s then
        r:Notify(
            {Title="MK 脚本",Description="已成功注入"},
            {OutlineColor=Color3.fromRGB(0,0,0),Time=6,Type="image"},
            {Image="rbxassetid://6023426923",ImageColor=Color3.fromRGB(255,58,68)}
        )
    end
end
_N()

--// 主脚本开始
local a=game:GetService("Players")local b=game:GetService("RunService")local c=game:GetService("UserInputService")local d=game:GetService("Lighting")local e=a.LocalPlayer
local f=Instance.new("ScreenGui")f.Name="U_"..tostring(math.random(1000,9999))f.ResetOnSpawn=false f.Parent=e:WaitForChild("PlayerGui")
local g=d.Brightness local h=d.Ambient local i=d.ColorShift_Top local j=d.ColorShift_Bottom
local k=Instance.new("TextButton")k.Size=UDim2.new(0,520,0,60)k.Position=UDim2.new(0.5,-260,0,10)k.BackgroundColor3=Color3.fromRGB(0,0,0)k.BackgroundTransparency=0.3 k.BorderSizePixel=0 k.AutoButtonColor=false k.Parent=f
local l=Instance.new("UICorner")l.CornerRadius=UDim.new(0,8)l.Parent=k
local m=false local n=nil local o=nil
local function p(q) q.InputBegan:Connect(function(r)if r.UserInputType==Enum.UserInputType.MouseButton1 then m=true n=r.Position o=q.Position end end)c.InputChanged:Connect(function(r)if m and r.UserInputType==Enum.UserInputType.MouseMovement then local s=r.Position-n q.Position=UDim2.new(o.X.Scale,o.X.Offset+s.X,o.Y.Scale,o.Y.Offset+s.Y)end end)c.InputEnded:Connect(function(r)if r.UserInputType==Enum.UserInputType.MouseButton1 then m=false end end)end p(k)
local r=Instance.new("TextButton")r.Size=UDim2.new(0,25,0,25)r.Position=UDim2.new(0,5,0,5)r.BackgroundColor3=Color3.fromRGB(150,0,0)r.BackgroundTransparency=0.3 r.Text="X"r.TextColor3=Color3.fromRGB(255,255,255)r.Font=Enum.Font.GothamBold r.TextSize=14 r.Parent=k
local s=Instance.new("UICorner")s.CornerRadius=UDim.new(0,4)s.Parent=r
local t=Instance.new("TextButton")t.Size=UDim2.new(0,25,0,25)t.Position=UDim2.new(1,-30,0,5)t.BackgroundColor3=Color3.fromRGB(0,100,0)t.BackgroundTransparency=0.3 t.Text="-"t.TextColor3=Color3.fromRGB(255,255,255)t.Font=Enum.Font.GothamBold t.TextSize=14 t.Parent=k
local u=Instance.new("UICorner")u.CornerRadius=UDim.new(0,4)u.Parent=t
local v=Instance.new("TextButton")v.Size=UDim2.new(0,40,0,40)v.Position=UDim2.new(1,-50,1,-50)v.BackgroundColor3=Color3.fromRGB(0,0,0)v.BackgroundTransparency=0.3 v.BorderSizePixel=0 v.Text=""v.Visible=false v.Active=true v.Parent=f
local w=Instance.new("UICorner")w.CornerRadius=UDim.new(0,4)w.Parent=v p(v)
local x={}local function y(z,A,B)local C=Instance.new("TextButton")C.Name=z C.Size=UDim2.new(0,120,0,40)C.Position=UDim2.new(0,B,0,10)C.BackgroundColor3=Color3.fromRGB(60,60,60)C.Text=A.." [OFF]"C.TextColor3=Color3.fromRGB(255,255,255)C.Font=Enum.Font.GothamBold C.TextSize=12 C.AutoButtonColor=false C.Parent=k local D=Instance.new("UICorner")D.CornerRadius=UDim.new(1,0)D.Parent=C return C end x.playerEsp=y("pe","玩家透视",10)x.npcEsp=y("ne","NPC透视",140)x.aimbot=y("ab","平滑自瞄",270)x.highlight=y("hl","高亮",400)
local E={}local F=true local G={}local H={}local I=false local J=false
r.MouseButton1Click:Connect(function()for _,K in pairs(E)do if K then K:Disconnect()end end for _,L in pairs(G)do if L.Highlight then L.Highlight:Destroy()end if L.Billboard then L.Billboard:Destroy()end end for _,M in pairs(H)do if M.Highlight then M.Highlight:Destroy()end if M.Billboard then M.Billboard:Destroy()end end d.Brightness=g d.Ambient=h d.ColorShift_Top=i d.ColorShift_Bottom=j f:Destroy()end)
local N=false t.MouseButton1Click:Connect(function()N=not N k.Visible=not N v.Visible=N t.Text=N and"+"or"-"end)v.MouseButton1Click:Connect(function()N=false k.Visible=true v.Visible=false t.Text="-"end)
x.playerEsp.MouseButton1Click:Connect(function()if not E.playerEsp then E.playerEsp=b.RenderStepped:Connect(function()for _,O in pairs(a:GetPlayers())do if O~=e and O.Character and O.Character:FindFirstChild("Humanoid")and O.Character:FindFirstChild("Head")then if not G[O]then local P=Instance.new("Highlight")P.Adornee=O.Character P.FillColor=Color3.fromRGB(0,255,0)P.FillTransparency=0.8 P.OutlineColor=Color3.fromRGB(50,255,50)P.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop P.Parent=O.Character local Q=Instance.new("BillboardGui")Q.Size=UDim2.new(0,120,0,40)Q.Adornee=O.Character.Head Q.AlwaysOnTop=true Q.StudsOffset=Vector3.new(0,2,0)Q.Parent=O.Character.Head local R=Instance.new("TextLabel")R.Size=UDim2.new(1,0,0.5,0)R.BackgroundTransparency=1 R.TextColor3=Color3.fromRGB(200,255,200)R.TextStrokeTransparency=0 R.Text=O.Name R.Parent=Q local S=Instance.new("TextLabel")S.Size=UDim2.new(1,0,0.5,0)S.Position=UDim2.new(0,0,0.5,0)S.BackgroundTransparency=1 S.TextColor3=Color3.fromRGB(100,255,100)S.TextStrokeTransparency=0 S.Text="HP: "..math.floor(O.Character.Humanoid.Health)S.Parent=Q G[O]={Highlight=P,Billboard=Q,HealthLabel=S,Humanoid=O.Character.Humanoid}else G[O].HealthLabel.Text="HP: "..math.floor(G[O].Humanoid.Health)end end end)buttons.playerEsp.BackgroundColor3=Color3.fromRGB(0,150,0)buttons.playerEsp.Text="玩家透视 [ON]"else E.playerEsp:Disconnect()E.playerEsp=nil for _,T in pairs(G)do if T.Highlight then T.Highlight:Destroy()end if T.Billboard then T.Billboard:Destroy()end end G={}buttons.playerEsp.BackgroundColor3=Color3.fromRGB(60,60,60)buttons.playerEsp.Text="玩家透视 [OFF]"end end)
x.npcEsp.MouseButton1Click:Connect(function()if not E.npcEsp then E.npcEsp=b.RenderStepped:Connect(function()for _,U in pairs(workspace:GetDescendants())do if U:IsA("Model")and U:FindFirstChild("Humanoid")and U:FindFirstChild("Head")and not a:GetPlayerFromCharacter(U)then if not H[U]then local V=Instance.new("Highlight")V.Adornee=U V.FillColor=Color3.fromRGB(255,0,0)V.FillTransparency=0.8 V.OutlineColor=Color3.fromRGB(255,50,50)V.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop V.Parent=U local W=Instance.new("BillboardGui")W.Size=UDim2.new(0,120,0,40)W.Adornee=U.Head W.AlwaysOnTop=true W.StudsOffset=Vector3.new(0,2,0)W.Parent=U.Head local X=Instance.new("TextLabel")X.Size=UDim2.new(1,0,0.5,0)X.BackgroundTransparency=1 X.TextColor3=Color3.fromRGB(255,200,200)X.TextStrokeTransparency=0 X.Text=U.Name X.Parent=W local Y=Instance.new("TextLabel")Y.Size=UDim2.new(1,0,0.5,0)Y.Position=UDim2.new(0,0,0.5,0)Y.BackgroundTransparency=1 Y.TextColor3=Color3.fromRGB(255,100,100)Y.TextStrokeTransparency=0 Y.Text="HP: "..math.floor(U.Humanoid.Health)Y.Parent=W H[U]={Highlight=V,Billboard=W,HealthLabel=Y,Humanoid=U.Humanoid}else H[U].HealthLabel.Text="HP: "..math.floor(H[U].Humanoid.Health)end end end)buttons.npcEsp.BackgroundColor3=Color3.fromRGB(150,0,0)buttons.npcEsp.Text="NPC透视 [ON]"else E.npcEsp:Disconnect()E.npcEsp=nil for _,Z in pairs(H)do if Z.Highlight then Z.Highlight:Destroy()end if Z.Billboard then Z.Billboard:Destroy()end end H={}buttons.npcEsp.BackgroundColor3=Color3.fromRGB(60,60,60)buttons.npcEsp.Text="NPC透视 [OFF]"end end)
x.aimbot.MouseButton1Click:Connect(function()I=not I if I then buttons.aimbot.BackgroundColor3=Color3.fromRGB(0,0,150)buttons.aimbot.Text="平滑自瞄 [ON]"if F then F=false local aa=Instance.new("Frame")aa.Size=UDim2.new(0,280,0,70)aa.Position=UDim2.new(0.5,-140,0.8,0)aa.BackgroundColor3=Color3.fromRGB(0,0,0)aa.BackgroundTransparency=0.3 aa.Parent=f local ab=Instance.new("UICorner")ab.CornerRadius=UDim.new(0,8)ab.Parent=aa local ac=Instance.new("TextLabel")ac.Size=UDim2.new(1,0,1,0)ac.BackgroundTransparency=1 ac.Text="平滑自瞄已启用\n包含玩家与NPC（带预判）"ac.TextColor3=Color3.fromRGB(255,255,255)ac.Font=Enum.Font.Gotham ac.TextSize=16 ac.TextWrapped=true ac.Parent=aa task.delay(3,function()aa:Destroy()end)end if not E.aimbot then local ad=0.12 local ae=300 local af=60 local ag=0.15 local ah=workspace.CurrentCamera local ai={}local function aj()if e.Character and e.Character:FindFirstChild("HumanoidRootPart")then return e.Character end return nil end local function ak(al)local am=ah.CFrame.Position local an=(al-am).Unit local ao=ah.CFrame.LookVector local ap=ao:Dot(an)local aq=math.acos(ap)*(180/math.pi)return aq<=af/2 end local function ar(as,at)local au=tostring(as:GetDebugId())if not ai[au]then ai[au]={lastPos=at,lastTime=tick(),velocity=Vector3.new(0,0,0)}return at end local av=ai[au]local aw=tick()local ax=aw-av.lastTime if ax>0 then local ay=(at-av.lastPos)/ax av.velocity=av.velocity:Lerp(ay,0.3)local az=at+(av.velocity*ag)av.lastPos=at av.lastTime=aw return az end return at end local function aA()local ba=aj()if not ba then return nil end local bb=ba.HumanoidRootPart.Position local bc=nil local bd=ae for _,be in pairs(a:GetPlayers())do if be~=e and be.Character and be.Character:FindFirstChild("HumanoidRootPart")then local bf=be.Character.HumanoidRootPart.Position local bg=(bb-bf).Magnitude if bg<bd and ak(bf)then bd=bg bc=be.Character.HumanoidRootPart end end end for _,bh in pairs(workspace:GetDescendants())do if bh:IsA("Model")and bh:FindFirstChild("HumanoidRootPart")then local bi=false for _,bj in pairs(a:GetPlayers())do if bj.Character==bh then bi=true break end end if not bi then local bk=bh.HumanoidRootPart.Position local bl=(bb-bk).Magnitude if bl<bd and ak(bk)then bd=bl bc=bh.HumanoidRootPart end end end end return bc end E.aimbot=b.Heartbeat:Connect(function()pcall(function()local bm=aA()if bm then local bn=bm.Position local bo=ar(bm,bn)local bp=ah.CFrame.Position local bq=(bo-bp).Unit local br=CFrame.lookAt(bp,bp+bq)local bs=Vector3.new((math.random()-0.5)*0.02,(math.random()-0.5)*0.02,0)ah.CFrame=ah.CFrame:Lerp(br+bs,ad)end end)end)end else buttons.aimbot.BackgroundColor3=Color3.fromRGB(60,60,60)buttons.aimbot.Text="平滑自瞄 [OFF]"if E.aimbot then E.aimbot:Disconnect()E.aimbot=nil end end end)
x.highlight.MouseButton1Click:Connect(function()J=not J if J then buttons.highlight.BackgroundColor3=Color3.fromRGB(150,150,0)buttons.highlight.Text="高亮 [ON]"d.Brightness=5 d.Ambient=Color3.fromRGB(255,255,255)d.ColorShift_Top=Color3.fromRGB(255,255,255)d.ColorShift_Bottom=Color3.fromRGB(255,255,255)else buttons.highlight.BackgroundColor3=Color3.fromRGB(60,60,60)buttons.highlight.Text="高亮 [OFF]"d.Brightness=g d.Ambient=h d.ColorShift_Top=i d.ColorShift_Bottom=j end end)
